### ISSUE TITLE
所以网页版是失效了吗

### ISSUE THREAD

**Issue by xiaotianxt** [PKUNoRun/pkunorun.github.io#1]
用模拟器配置了半天还是不行，请问使用的模拟器安卓版本和cpu架构是什么呢？

**Comment by HamiltonHuaji** [comment]
Android 10.0, x86_64

**Comment by HamiltonHuaji** [comment]
网页版应该还能用...吧. 只不过比较复杂不推荐用.

**Comment by xiaotianxt** [comment]
> 网页版应该还能用...吧. 只不过比较复杂不推荐用.

好的，我再试试
